table dim_date
	lineageTag: ccf7451b-3133-41df-b942-5b12ab6614aa

	measure _ddMinDate = MIN(dim_date[date])
		formatString: General Date
		lineageTag: 40a7a1f2-25b0-4133-b682-9c3db72565c4

	measure _ddMaxDate = MAX(dim_date[date])
		formatString: General Date
		lineageTag: f90173df-6d40-4eae-b4d0-1718dddf0e3b

	measure '+ddMinDate(d mmmm YYYY)' = FORMAT([_ddMinDate], "d mmmm YYYY")
		lineageTag: 83664c49-2d41-451e-9a8b-7ff8be90ebba

	measure '+ddMaxDate(d mmmm YYYY)' = FORMAT([_ddMaxDate], "d mmmm YYYY")
		lineageTag: 3ba0ba12-3d6f-48f9-a571-6e8047b5f735

	measure +DateRange =
			
			IF(
			    [_ddMinDate] = [_ddMaxDate],
			    [+ddMinDate(d mmmm YYYY)],  // if the min = max then the user has 1 date selected
			    [+ddMinDate(d mmmm YYYY)] & " - " & [+ddMaxDate(d mmmm YYYY)]  //otherwise show the range
			)
		lineageTag: ebc83cb9-7eec-4756-a88c-854c67b41a8f

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5c45d6f4-5f04-450f-939e-98bae1000c97
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column dim_date_key
		dataType: string
		lineageTag: 6daab444-1d80-4cca-a944-b47f598acbb4
		summarizeBy: none
		sourceColumn: dim_date_key

	column year
		dataType: int64
		formatString: 0
		lineageTag: 5c724fc6-041b-4f34-9926-544e3d3d6778
		summarizeBy: none
		sourceColumn: year

	column month
		dataType: int64
		formatString: 0
		lineageTag: 10464593-d09a-496e-ab35-b20a37aa80d9
		summarizeBy: none
		sourceColumn: month

	column day
		dataType: int64
		formatString: 0
		lineageTag: 2e12d846-b186-4123-a275-fe16e2721337
		summarizeBy: none
		sourceColumn: day

	column iso_week
		dataType: int64
		formatString: 0
		lineageTag: 3ca0a94c-d288-4539-a3ee-5d81514862c5
		summarizeBy: none
		sourceColumn: iso_week

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 0ae2c854-a639-4f0a-b268-71d8fb51ff6c
		summarizeBy: none
		sourceColumn: quarter

	partition dim_date = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"personal-portfolio-477421" = Source{[Name="personal-portfolio-477421"]}[Data],
				    ga4_analytics_Schema = #"personal-portfolio-477421"{[Name="ga4_analytics",Kind="Schema"]}[Data],
				    dim_date_Table = ga4_analytics_Schema{[Name="dim_date",Kind="Table"]}[Data]
				in
				    dim_date_Table

	annotation PBI_ResultType = Table

