table fact_page_metrics
	lineageTag: 4dbf6492-61d5-4904-a063-5da39580f2b2

	measure _fpmSumActiveUsers = SUM(fact_page_metrics[active_users])
		formatString: #,0
		lineageTag: e35e1c70-2b0a-4831-b07b-78a0c01ca5ba

	measure _fpmSumEventCount = SUM(fact_page_metrics[event_count])
		formatString: #,0
		lineageTag: f9ac867c-0870-48b8-858d-a83b8b0e141a

	measure _fpmSumKeyEvents = SUM(fact_page_metrics[key_events])
		formatString: #,0
		lineageTag: f42602f1-9cb2-4a2f-ac7e-050762822016

	measure _fpmSumScreenPageViews = SUM(fact_page_metrics[screen_page_views])
		formatString: #,0
		lineageTag: b02944da-4e26-4370-af3f-71f853c164ba

	measure _fpmAvgUserEngagementDuration = AVERAGE(fact_page_metrics[user_engagement_duration])
		formatString: #,0.00
		lineageTag: a3276a11-14bc-4d6d-aa62-9fc7b51c49d5

	measure '+fpmAvgUserEngagementDurationPerSession(Minutes:Seconds):VAR _Minutes' = ```
			
			
			VAR _Minutes = QUOTIENT([_fpmAvgUserEngagementDuration], 60)
			
			VAR _Seconds = INT(MOD([_fpmAvgUserEngagementDuration], 60))
			
			VAR _MinutesString = IF(NOT ISBLANK(_Minutes), _Minutes & " Minutes ")
			VAR _SecondsString = IF(NOT ISBLANK(_Seconds), _Seconds & " Seconds") 
			
			
			
			RETURN _MinutesString & _SecondsString
			```
		lineageTag: 8258b9b0-34be-4be9-9014-9035a9fe7133

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b8d49df-5aa8-42f7-a75d-4739638ca7a9
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column dim_date_key
		dataType: string
		lineageTag: b02b2cb1-524c-499d-aa26-20e0129529dc
		summarizeBy: none
		sourceColumn: dim_date_key

	column dim_page_key
		dataType: int64
		formatString: 0
		lineageTag: 9ced63d1-f366-4517-8e40-027f52070223
		summarizeBy: none
		sourceColumn: dim_page_key

	column active_users
		dataType: int64
		formatString: 0
		lineageTag: add5207e-1dd6-42af-991f-82be107888b2
		summarizeBy: none
		sourceColumn: active_users

	column event_count
		dataType: int64
		formatString: 0
		lineageTag: 6d4f99c7-a739-4dc0-807a-ca78d6c7eeaa
		summarizeBy: none
		sourceColumn: event_count

	column key_events
		dataType: double
		lineageTag: 1f5bfb27-93ab-43b5-aa77-ea60fb4785e2
		summarizeBy: none
		sourceColumn: key_events

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column screen_page_views
		dataType: int64
		formatString: 0
		lineageTag: 00884d3d-fb24-414c-8368-1752d715d490
		summarizeBy: none
		sourceColumn: screen_page_views

	column screen_page_views_per_user
		dataType: double
		lineageTag: 17a8e096-8c58-43a8-ab3e-f03147d26ab2
		summarizeBy: none
		sourceColumn: screen_page_views_per_user

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_revenue
		dataType: double
		lineageTag: 33a876be-fac9-4bb2-9712-78b3e947601c
		summarizeBy: none
		sourceColumn: total_revenue

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column user_engagement_duration
		dataType: double
		lineageTag: aabdfb13-d0c5-4023-87c4-a33864158be7
		summarizeBy: none
		sourceColumn: user_engagement_duration

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_page_metrics = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"personal-portfolio-477421" = Source{[Name="personal-portfolio-477421"]}[Data],
				    ga4_analytics_Schema = #"personal-portfolio-477421"{[Name="ga4_analytics",Kind="Schema"]}[Data],
				    fact_page_metrics_Table = ga4_analytics_Schema{[Name="fact_page_metrics",Kind="Table"]}[Data]
				in
				    fact_page_metrics_Table

	annotation PBI_ResultType = Table

